// c2.v generated by perl script

module c2 (s__1, a__0, b__0, a__1, b__1);
	output s__1;
	wire n26, n25;
	input a__0, b__0, a__1, b__1;
  assign s__1 = n25 ^ n26;
  assign n25 = b__0 & a__0;
  assign n26 = b__1 ^ a__1;
endmodule
