// c3.v generated by perl script

module c3 (s__2, a__2, b__2, b__0, a__0, b__1, a__1);
	output s__2;
	wire n18, n20, n22, n21, n23, n24;
	input a__2, b__2, b__0, a__0, b__1, a__1;
  assign s__2 = n20 ^ n18;
  assign n20 = b__2 ^ a__2;
  assign n18 = n21 | n22;
  assign n21 = n23 & b__0;
  assign n23 = a__0 & n24;
  assign n24 = a__1 | b__1;
  assign n22 = b__1 & a__1;
endmodule
