// c4.v generated by perl script

module c4 (s__3, a__3, b__3, b__2, a__2, b__0, a__0, b__1, a__1);
	output s__3;
	wire n15, n14, n17, n16, n19, n18, n22, n21, n23, n24;
	input a__3, b__3, b__2, a__2, b__0, a__0, b__1, a__1;
  assign s__3 = n14 ^ n15;
  assign n14 = b__3 ^ a__3;
  assign n15 = n16 | n17;
  assign n16 = b__2 & n19;
  assign n19 = a__2 | n18;
  assign n18 = n21 | n22;
  assign n21 = n23 & b__0;
  assign n23 = a__0 & n24;
  assign n24 = a__1 | b__1;
  assign n22 = b__1 & a__1;
  assign n17 = a__2 & n18;
endmodule
