woc_gencla: constants.v gen_nonlinear_part.v gen_linear_part.v gen_cla_decomposed.v tb_gen_cla_decomposed.v
	iverilog gen_nonlinear_part.v gen_linear_part.v gen_cla_decomposed.v tb_gen_cla_decomposed.v -o woc_gencla

test:
	./woc_gencla


