// c105.v generated by perl script

module c105 (n__104, b__4, b__3, b__2, a__2);
	output n__104;
	wire n650, n__41, n629, n631;
	input b__4, b__3, b__2, a__2;
  assign n__104 = ~n650;
  assign n650 = ~(n__41 & b__4);
  assign n__41 = ~(n631 | n629);
  assign n631 = ~b__3;
  assign n629 = ~(a__2 & b__2);
endmodule
