// c121.v generated by perl script

module c121 (n__120, a__5, b__4, a__4);
	output n__120;
	wire n568, n__56, n632;
	input a__5, b__4, a__4;
  assign n__120 = ~n568;
  assign n568 = ~(a__5 & n__56);
  assign n__56 = ~n632;
  assign n632 = ~(a__4 & b__4);
endmodule
