// c172.v generated by perl script

module c172 (n__171, a__5, b__4, b__3, a__2, a__1, c, a__0);
	output n__171;
	wire n517, n__107, n644, n__44, n607, n631, n__5, n576, n645;
	input a__5, b__4, b__3, a__2, a__1, c, a__0;
  assign n__171 = ~n517;
  assign n517 = ~(a__5 & n__107);
  assign n__107 = ~n644;
  assign n644 = ~(n__44 & b__4);
  assign n__44 = ~(n631 | n607);
  assign n631 = ~b__3;
  assign n607 = ~(a__2 & n__5);
  assign n__5 = ~(n645 | n576);
  assign n645 = ~a__1;
  assign n576 = ~(a__0 & c);
endmodule
