// c266.v generated by perl script

module c266 (n__265, a__5, a__4, b__3, b__2, a__2, a__6);
	output n__265;
	wire n434, n551, n__73, n610, n__41, n629, n631;
	input a__5, a__4, b__3, b__2, a__2, a__6;
  assign n__265 = ~(n551 | n434);
  assign n551 = ~(a__5 & n__73);
  assign n__73 = ~n610;
  assign n610 = ~(n__41 & a__4);
  assign n__41 = ~(n631 | n629);
  assign n631 = ~b__3;
  assign n629 = ~(a__2 & b__2);
  assign n434 = ~a__6;
endmodule
