// c296.v generated by perl script

module c296 (n__295, a__5, b__4, b__2, b__1, b__0, c, a__3, a__6);
	output n__295;
	wire n436, n521, n__103, n651, n__40, n616, n571, n__9, n570, n649;
	input a__5, b__4, b__2, b__1, b__0, c, a__3, a__6;
  assign n__295 = ~(n521 | n436);
  assign n521 = ~(a__5 & n__103);
  assign n__103 = ~n651;
  assign n651 = ~(n__40 & b__4);
  assign n__40 = ~(n571 | n616);
  assign n571 = ~(n__9 & b__2);
  assign n__9 = ~(n649 | n570);
  assign n649 = ~b__1;
  assign n570 = ~(c & b__0);
  assign n616 = ~a__3;
  assign n436 = ~a__6;
endmodule
