// c304.v generated by perl script

module c304 (n__303, a__5, b__4, b__3, a__2, b__1, b__0, c, a__6);
	output n__303;
	wire n437, n513, n__111, n640, n__48, n579, n631, n__9, n570, n649;
	input a__5, b__4, b__3, a__2, b__1, b__0, c, a__6;
  assign n__303 = ~(n513 | n437);
  assign n513 = ~(a__5 & n__111);
  assign n__111 = ~n640;
  assign n640 = ~(n__48 & b__4);
  assign n__48 = ~(n631 | n579);
  assign n631 = ~b__3;
  assign n579 = ~(a__2 & n__9);
  assign n__9 = ~(n649 | n570);
  assign n649 = ~b__1;
  assign n570 = ~(c & b__0);
  assign n437 = ~a__6;
endmodule
