// c312.v generated by perl script

module c312 (n__311, b__5, b__4, a__4, a__6);
	output n__311;
	wire n438, n505, n__56, n632;
	input b__5, b__4, a__4, a__6;
  assign n__311 = ~(n505 | n438);
  assign n505 = ~(n__56 & b__5);
  assign n__56 = ~n632;
  assign n632 = ~(a__4 & b__4);
  assign n438 = ~a__6;
endmodule
