// c313.v generated by perl script

module c313 (n__312, b__5, a__4, b__3, a__3, a__6);
	output n__312;
	wire n438, n504, n__57, n630, n__25, n616, n631;
	input b__5, a__4, b__3, a__3, a__6;
  assign n__312 = ~(n504 | n438);
  assign n504 = ~(n__57 & b__5);
  assign n__57 = ~n630;
  assign n630 = ~(a__4 & n__25);
  assign n__25 = ~(n631 | n616);
  assign n631 = ~b__3;
  assign n616 = ~a__3;
  assign n438 = ~a__6;
endmodule
