// c355.v generated by perl script

module c355 (n__354, b__5, b__4, a__3, b__2, a__1, c, a__0, a__6);
	output n__354;
	wire n441, n462, n__99, n581, n__36, n575, n616, n__5, n576, n645;
	input b__5, b__4, a__3, b__2, a__1, c, a__0, a__6;
  assign n__354 = ~(n462 | n441);
  assign n462 = ~(n__99 & b__5);
  assign n__99 = ~n581;
  assign n581 = ~(b__4 & n__36);
  assign n__36 = ~(n616 | n575);
  assign n616 = ~a__3;
  assign n575 = ~(b__2 & n__5);
  assign n__5 = ~(n645 | n576);
  assign n645 = ~a__1;
  assign n576 = ~(a__0 & c);
  assign n441 = ~a__6;
endmodule
