// c385.v generated by perl script

module c385 (n__384, b__6, a__5, a__4, a__2, b__1, b__0, c, a__3);
	output n__384;
	wire n559, n423, n__65, n620, n__33, n616, n579, n__9, n570, n649;
	input b__6, a__5, a__4, a__2, b__1, b__0, c, a__3;
  assign n__384 = ~(n423 | n559);
  assign n423 = ~b__6;
  assign n559 = ~(a__5 & n__65);
  assign n__65 = ~n620;
  assign n620 = ~(a__4 & n__33);
  assign n__33 = ~(n579 | n616);
  assign n579 = ~(a__2 & n__9);
  assign n__9 = ~(n649 | n570);
  assign n649 = ~b__1;
  assign n570 = ~(c & b__0);
  assign n616 = ~a__3;
endmodule
