// c393.v generated by perl script

module c393 (n__392, b__6, a__5, a__4, b__3, b__2, a__2);
	output n__392;
	wire n551, n424, n__73, n610, n__41, n629, n631;
	input b__6, a__5, a__4, b__3, b__2, a__2;
  assign n__392 = ~(n424 | n551);
  assign n424 = ~b__6;
  assign n551 = ~(a__5 & n__73);
  assign n__73 = ~n610;
  assign n610 = ~(n__41 & a__4);
  assign n__41 = ~(n631 | n629);
  assign n631 = ~b__3;
  assign n629 = ~(a__2 & b__2);
endmodule
