// c397.v generated by perl script

module c397 (n__396, b__6, a__5, a__4, b__3, a__2, a__1, b__0, c);
	output n__396;
	wire n547, n424, n__77, n605, n__45, n596, n631, n__6, n570, n645;
	input b__6, a__5, a__4, b__3, a__2, a__1, b__0, c;
  assign n__396 = ~(n424 | n547);
  assign n424 = ~b__6;
  assign n547 = ~(a__5 & n__77);
  assign n__77 = ~n605;
  assign n605 = ~(n__45 & a__4);
  assign n__45 = ~(n631 | n596);
  assign n631 = ~b__3;
  assign n596 = ~(n__6 & a__2);
  assign n__6 = ~(n645 | n570);
  assign n645 = ~a__1;
  assign n570 = ~(c & b__0);
endmodule
