// c4.v generated by perl script

module c4 (n__3, a__1, b__1);
	output n__3;
	wire n649, n645;
	input a__1, b__1;
  assign n__3 = ~(n645 | n649);
  assign n645 = ~a__1;
  assign n649 = ~b__1;
endmodule
