// c439.v generated by perl script

module c439 (n__438, b__6, b__5, b__4, a__4);
	output n__438;
	wire n505, n428, n__56, n632;
	input b__6, b__5, b__4, a__4;
  assign n__438 = ~(n428 | n505);
  assign n428 = ~b__6;
  assign n505 = ~(n__56 & b__5);
  assign n__56 = ~n632;
  assign n632 = ~(a__4 & b__4);
endmodule
