// c472.v generated by perl script

module c472 (n__471, b__6, b__5, b__4, b__2, a__2, a__3);
	output n__471;
	wire n472, n430, n__89, n592, n__26, n616, n629;
	input b__6, b__5, b__4, b__2, a__2, a__3;
  assign n__471 = ~(n430 | n472);
  assign n430 = ~b__6;
  assign n472 = ~(n__89 & b__5);
  assign n__89 = ~n592;
  assign n592 = ~(n__26 & b__4);
  assign n__26 = ~(n629 | n616);
  assign n629 = ~(a__2 & b__2);
  assign n616 = ~a__3;
endmodule
