// c477.v generated by perl script

module c477 (n__476, b__6, b__5, b__4, a__2, b__0, a__0, b__1, a__3);
	output n__476;
	wire n467, n430, n__94, n587, n__31, n616, n585, n__7, n649, n647;
	input b__6, b__5, b__4, a__2, b__0, a__0, b__1, a__3;
  assign n__476 = ~(n430 | n467);
  assign n430 = ~b__6;
  assign n467 = ~(n__94 & b__5);
  assign n__94 = ~n587;
  assign n587 = ~(n__31 & b__4);
  assign n__31 = ~(n585 | n616);
  assign n585 = ~(n__7 & a__2);
  assign n__7 = ~(n647 | n649);
  assign n647 = ~(a__0 & b__0);
  assign n649 = ~b__1;
  assign n616 = ~a__3;
endmodule
