// c499.v generated by perl script

module c499 (n__498, b__6, b__5, b__4, b__2, b__0, a__0, b__1, b__3);
	output n__498;
	wire n445, n432, n__116, n635, n__53, n631, n573, n__7, n649, n647;
	input b__6, b__5, b__4, b__2, b__0, a__0, b__1, b__3;
  assign n__498 = ~(n432 | n445);
  assign n432 = ~b__6;
  assign n445 = ~(n__116 & b__5);
  assign n__116 = ~n635;
  assign n635 = ~(n__53 & b__4);
  assign n__53 = ~(n573 | n631);
  assign n573 = ~(n__7 & b__2);
  assign n__7 = ~(n647 | n649);
  assign n647 = ~(a__0 & b__0);
  assign n649 = ~b__1;
  assign n631 = ~b__3;
endmodule
