// c500.v generated by perl script

module c500 (n__499, b__6, b__5, b__4, b__2, c, a__0, b__1, b__3);
	output n__499;
	wire n444, n432, n__117, n634, n__54, n631, n572, n__8, n649, n576;
	input b__6, b__5, b__4, b__2, c, a__0, b__1, b__3;
  assign n__499 = ~(n432 | n444);
  assign n432 = ~b__6;
  assign n444 = ~(n__117 & b__5);
  assign n__117 = ~n634;
  assign n634 = ~(n__54 & b__4);
  assign n__54 = ~(n572 | n631);
  assign n572 = ~(n__8 & b__2);
  assign n__8 = ~(n576 | n649);
  assign n576 = ~(a__0 & c);
  assign n649 = ~b__1;
  assign n631 = ~b__3;
endmodule
