// c52.v generated by perl script

module c52 (n__51, b__3, b__2, a__1, c, a__0);
	output n__51;
	wire n575, n631, n__5, n576, n645;
	input b__3, b__2, a__1, c, a__0;
  assign n__51 = ~(n631 | n575);
  assign n631 = ~b__3;
  assign n575 = ~(b__2 & n__5);
  assign n__5 = ~(n645 | n576);
  assign n645 = ~a__1;
  assign n576 = ~(a__0 & c);
endmodule
