// c58.v generated by perl script

module c58 (n__57, a__4, b__3, a__3);
	output n__57;
	wire n630, n__25, n616, n631;
	input a__4, b__3, a__3;
  assign n__57 = ~n630;
  assign n630 = ~(a__4 & n__25);
  assign n__25 = ~(n631 | n616);
  assign n631 = ~b__3;
  assign n616 = ~a__3;
endmodule
