// c123.v generated by perl script

module c123 (n__122, a__5, a__4, b__2, a__2, a__3);
	output n__122;
	wire n566, n__58, n628, n__26, n616, n629;
	input a__5, a__4, b__2, a__2, a__3;
  assign n__122 = ~n566;
  assign n566 = ~(a__5 & n__58);
  assign n__58 = ~n628;
  assign n628 = ~(a__4 & n__26);
  assign n__26 = ~(n629 | n616);
  assign n629 = ~(a__2 & b__2);
  assign n616 = ~a__3;
endmodule
