// c138.v generated by perl script

module c138 (n__137, a__5, a__4, b__3, b__2, a__2);
	output n__137;
	wire n551, n__73, n610, n__41, n629, n631;
	input a__5, a__4, b__3, b__2, a__2;
  assign n__137 = ~n551;
  assign n551 = ~(a__5 & n__73);
  assign n__73 = ~n610;
  assign n610 = ~(n__41 & a__4);
  assign n__41 = ~(n631 | n629);
  assign n631 = ~b__3;
  assign n629 = ~(a__2 & b__2);
endmodule
