// c16.v generated by perl script

module c16 (n__15, a__2, b__0, a__0, b__1);
	output n__15;
	wire n585, n__7, n649, n647;
	input a__2, b__0, a__0, b__1;
  assign n__15 = ~n585;
  assign n585 = ~(n__7 & a__2);
  assign n__7 = ~(n647 | n649);
  assign n647 = ~(a__0 & b__0);
  assign n649 = ~b__1;
endmodule
