// c18.v generated by perl script

module c18 (n__17, a__2, b__1, b__0, c);
	output n__17;
	wire n579, n__9, n570, n649;
	input a__2, b__1, b__0, c;
  assign n__17 = ~n579;
  assign n579 = ~(a__2 & n__9);
  assign n__9 = ~(n649 | n570);
  assign n649 = ~b__1;
  assign n570 = ~(c & b__0);
endmodule
