// c199.v generated by perl script

module c199 (n__198, b__5, a__4, b__2, c, a__0, b__1, a__3);
	output n__198;
	wire n490, n__71, n612, n__39, n616, n572, n__8, n649, n576;
	input b__5, a__4, b__2, c, a__0, b__1, a__3;
  assign n__198 = ~n490;
  assign n490 = ~(n__71 & b__5);
  assign n__71 = ~n612;
  assign n612 = ~(n__39 & a__4);
  assign n__39 = ~(n572 | n616);
  assign n572 = ~(n__8 & b__2);
  assign n__8 = ~(n576 | n649);
  assign n576 = ~(a__0 & c);
  assign n649 = ~b__1;
  assign n616 = ~a__3;
endmodule
