// c207.v generated by perl script

module c207 (n__206, b__5, a__4, b__3, a__2, c, a__0, b__1);
	output n__206;
	wire n482, n__79, n603, n__47, n580, n631, n__8, n649, n576;
	input b__5, a__4, b__3, a__2, c, a__0, b__1;
  assign n__206 = ~n482;
  assign n482 = ~(n__79 & b__5);
  assign n__79 = ~n603;
  assign n603 = ~(n__47 & a__4);
  assign n__47 = ~(n631 | n580);
  assign n631 = ~b__3;
  assign n580 = ~(n__8 & a__2);
  assign n__8 = ~(n576 | n649);
  assign n576 = ~(a__0 & c);
  assign n649 = ~b__1;
endmodule
