// c240.v generated by perl script

module c240 (n__239, b__5, b__4, b__3, b__2, a__1, b__1);
	output n__239;
	wire n449, n__112, n639, n__49, n578, n631, n__3, n649, n645;
	input b__5, b__4, b__3, b__2, a__1, b__1;
  assign n__239 = ~n449;
  assign n449 = ~(n__112 & b__5);
  assign n__112 = ~n639;
  assign n639 = ~(n__49 & b__4);
  assign n__49 = ~(n631 | n578);
  assign n631 = ~b__3;
  assign n578 = ~(n__3 & b__2);
  assign n__3 = ~(n645 | n649);
  assign n645 = ~a__1;
  assign n649 = ~b__1;
endmodule
