// c25.v generated by perl script

module c25 (n__24, b__2, b__1, b__0, c);
	output n__24;
	wire n571, n__9, n570, n649;
	input b__2, b__1, b__0, c;
  assign n__24 = ~n571;
  assign n571 = ~(n__9 & b__2);
  assign n__9 = ~(n649 | n570);
  assign n649 = ~b__1;
  assign n570 = ~(c & b__0);
endmodule
