// c251.v generated by perl script

module c251 (n__250, a__5, a__4, b__2, a__2, a__3, a__6);
	output n__250;
	wire n433, n566, n__58, n628, n__26, n616, n629;
	input a__5, a__4, b__2, a__2, a__3, a__6;
  assign n__250 = ~(n566 | n433);
  assign n566 = ~(a__5 & n__58);
  assign n__58 = ~n628;
  assign n628 = ~(a__4 & n__26);
  assign n__26 = ~(n629 | n616);
  assign n629 = ~(a__2 & b__2);
  assign n616 = ~a__3;
  assign n433 = ~a__6;
endmodule
