// c252.v generated by perl script

module c252 (n__251, a__5, a__4, a__2, a__1, b__1, a__3, a__6);
	output n__251;
	wire n433, n565, n__59, n626, n__27, n616, n627, n__3, n649, n645;
	input a__5, a__4, a__2, a__1, b__1, a__3, a__6;
  assign n__251 = ~(n565 | n433);
  assign n565 = ~(a__5 & n__59);
  assign n__59 = ~n626;
  assign n626 = ~(a__4 & n__27);
  assign n__27 = ~(n627 | n616);
  assign n627 = ~(a__2 & n__3);
  assign n__3 = ~(n645 | n649);
  assign n645 = ~a__1;
  assign n649 = ~b__1;
  assign n616 = ~a__3;
  assign n433 = ~a__6;
endmodule
