// c293.v generated by perl script

module c293 (n__292, a__5, b__4, b__2, a__1, b__0, c, a__3, a__6);
	output n__292;
	wire n436, n524, n__100, n654, n__37, n616, n574, n__6, n570, n645;
	input a__5, b__4, b__2, a__1, b__0, c, a__3, a__6;
  assign n__292 = ~(n524 | n436);
  assign n524 = ~(a__5 & n__100);
  assign n__100 = ~n654;
  assign n654 = ~(n__37 & b__4);
  assign n__37 = ~(n574 | n616);
  assign n574 = ~(n__6 & b__2);
  assign n__6 = ~(n645 | n570);
  assign n645 = ~a__1;
  assign n570 = ~(c & b__0);
  assign n616 = ~a__3;
  assign n436 = ~a__6;
endmodule
