// c297.v generated by perl script

module c297 (n__296, a__5, b__4, b__3, b__2, a__2, a__6);
	output n__296;
	wire n436, n520, n__104, n650, n__41, n629, n631;
	input a__5, b__4, b__3, b__2, a__2, a__6;
  assign n__296 = ~(n520 | n436);
  assign n520 = ~(a__5 & n__104);
  assign n__104 = ~n650;
  assign n650 = ~(n__41 & b__4);
  assign n__41 = ~(n631 | n629);
  assign n631 = ~b__3;
  assign n629 = ~(a__2 & b__2);
  assign n436 = ~a__6;
endmodule
