// c306.v generated by perl script

module c306 (n__305, a__5, b__4, b__3, b__2, b__0, a__0, a__1, a__6);
	output n__305;
	wire n437, n511, n__113, n638, n__50, n577, n631, n__4, n645, n647;
	input a__5, b__4, b__3, b__2, b__0, a__0, a__1, a__6;
  assign n__305 = ~(n511 | n437);
  assign n511 = ~(a__5 & n__113);
  assign n__113 = ~n638;
  assign n638 = ~(n__50 & b__4);
  assign n__50 = ~(n631 | n577);
  assign n631 = ~b__3;
  assign n577 = ~(n__4 & b__2);
  assign n__4 = ~(n647 | n645);
  assign n647 = ~(a__0 & b__0);
  assign n645 = ~a__1;
  assign n437 = ~a__6;
endmodule
