// c326.v generated by perl script

module c326 (n__325, b__5, a__4, b__2, b__0, a__0, b__1, a__3, a__6);
	output n__325;
	wire n439, n491, n__70, n613, n__38, n616, n573, n__7, n649, n647;
	input b__5, a__4, b__2, b__0, a__0, b__1, a__3, a__6;
  assign n__325 = ~(n491 | n439);
  assign n491 = ~(n__70 & b__5);
  assign n__70 = ~n613;
  assign n613 = ~(n__38 & a__4);
  assign n__38 = ~(n573 | n616);
  assign n573 = ~(n__7 & b__2);
  assign n__7 = ~(n647 | n649);
  assign n647 = ~(a__0 & b__0);
  assign n649 = ~b__1;
  assign n616 = ~a__3;
  assign n439 = ~a__6;
endmodule
