// c33.v generated by perl script

module c33 (n__32, a__2, c, a__0, b__1, a__3);
	output n__32;
	wire n616, n580, n__8, n649, n576;
	input a__2, c, a__0, b__1, a__3;
  assign n__32 = ~(n580 | n616);
  assign n580 = ~(n__8 & a__2);
  assign n__8 = ~(n576 | n649);
  assign n576 = ~(a__0 & c);
  assign n649 = ~b__1;
  assign n616 = ~a__3;
endmodule
