// c331.v generated by perl script

module c331 (n__330, b__5, a__4, b__3, a__2, b__0, a__0, a__1, a__6);
	output n__330;
	wire n439, n486, n__75, n608, n__43, n619, n631, n__4, n645, n647;
	input b__5, a__4, b__3, a__2, b__0, a__0, a__1, a__6;
  assign n__330 = ~(n486 | n439);
  assign n486 = ~(n__75 & b__5);
  assign n__75 = ~n608;
  assign n608 = ~(n__43 & a__4);
  assign n__43 = ~(n631 | n619);
  assign n631 = ~b__3;
  assign n619 = ~(a__2 & n__4);
  assign n__4 = ~(n647 | n645);
  assign n647 = ~(a__0 & b__0);
  assign n645 = ~a__1;
  assign n439 = ~a__6;
endmodule
