// c333.v generated by perl script

module c333 (n__332, b__5, a__4, b__3, a__2, a__1, b__0, c, a__6);
	output n__332;
	wire n439, n484, n__77, n605, n__45, n596, n631, n__6, n570, n645;
	input b__5, a__4, b__3, a__2, a__1, b__0, c, a__6;
  assign n__332 = ~(n484 | n439);
  assign n484 = ~(n__77 & b__5);
  assign n__77 = ~n605;
  assign n605 = ~(n__45 & a__4);
  assign n__45 = ~(n631 | n596);
  assign n631 = ~b__3;
  assign n596 = ~(n__6 & a__2);
  assign n__6 = ~(n645 | n570);
  assign n645 = ~a__1;
  assign n570 = ~(c & b__0);
  assign n439 = ~a__6;
endmodule
