// c334.v generated by perl script

module c334 (n__333, b__5, a__4, b__3, a__2, b__0, a__0, b__1, a__6);
	output n__333;
	wire n439, n483, n__78, n604, n__46, n585, n631, n__7, n649, n647;
	input b__5, a__4, b__3, a__2, b__0, a__0, b__1, a__6;
  assign n__333 = ~(n483 | n439);
  assign n483 = ~(n__78 & b__5);
  assign n__78 = ~n604;
  assign n604 = ~(n__46 & a__4);
  assign n__46 = ~(n631 | n585);
  assign n631 = ~b__3;
  assign n585 = ~(n__7 & a__2);
  assign n__7 = ~(n647 | n649);
  assign n647 = ~(a__0 & b__0);
  assign n649 = ~b__1;
  assign n439 = ~a__6;
endmodule
