// c342.v generated by perl script

module c342 (n__341, b__5, a__4, b__2, c, a__0, b__1, b__3, a__6);
	output n__341;
	wire n440, n475, n__86, n595, n__54, n631, n572, n__8, n649, n576;
	input b__5, a__4, b__2, c, a__0, b__1, b__3, a__6;
  assign n__341 = ~(n475 | n440);
  assign n475 = ~(n__86 & b__5);
  assign n__86 = ~n595;
  assign n595 = ~(n__54 & a__4);
  assign n__54 = ~(n572 | n631);
  assign n572 = ~(n__8 & b__2);
  assign n__8 = ~(n576 | n649);
  assign n576 = ~(a__0 & c);
  assign n649 = ~b__1;
  assign n631 = ~b__3;
  assign n440 = ~a__6;
endmodule
