// c361.v generated by perl script

module c361 (n__360, b__5, b__4, b__3, a__2, a__1, b__1, a__6);
	output n__360;
	wire n441, n456, n__105, n648, n__42, n627, n631, n__3, n649, n645;
	input b__5, b__4, b__3, a__2, a__1, b__1, a__6;
  assign n__360 = ~(n456 | n441);
  assign n456 = ~(n__105 & b__5);
  assign n__105 = ~n648;
  assign n648 = ~(n__42 & b__4);
  assign n__42 = ~(n631 | n627);
  assign n631 = ~b__3;
  assign n627 = ~(a__2 & n__3);
  assign n__3 = ~(n645 | n649);
  assign n645 = ~a__1;
  assign n649 = ~b__1;
  assign n441 = ~a__6;
endmodule
