// c395.v generated by perl script

module c395 (n__394, b__6, a__5, a__4, b__3, a__2, b__0, a__0, a__1);
	output n__394;
	wire n549, n424, n__75, n608, n__43, n619, n631, n__4, n645, n647;
	input b__6, a__5, a__4, b__3, a__2, b__0, a__0, a__1;
  assign n__394 = ~(n424 | n549);
  assign n424 = ~b__6;
  assign n549 = ~(a__5 & n__75);
  assign n__75 = ~n608;
  assign n608 = ~(n__43 & a__4);
  assign n__43 = ~(n631 | n619);
  assign n631 = ~b__3;
  assign n619 = ~(a__2 & n__4);
  assign n__4 = ~(n647 | n645);
  assign n647 = ~(a__0 & b__0);
  assign n645 = ~a__1;
endmodule
