// c404.v generated by perl script

module c404 (n__403, b__6, a__5, a__4, b__2, a__1, b__0, c, b__3);
	output n__403;
	wire n540, n425, n__84, n598, n__52, n631, n574, n__6, n570, n645;
	input b__6, a__5, a__4, b__2, a__1, b__0, c, b__3;
  assign n__403 = ~(n425 | n540);
  assign n425 = ~b__6;
  assign n540 = ~(a__5 & n__84);
  assign n__84 = ~n598;
  assign n598 = ~(n__52 & a__4);
  assign n__52 = ~(n574 | n631);
  assign n574 = ~(n__6 & b__2);
  assign n__6 = ~(n645 | n570);
  assign n645 = ~a__1;
  assign n570 = ~(c & b__0);
  assign n631 = ~b__3;
endmodule
