// c475.v generated by perl script

module c475 (n__474, b__6, b__5, b__4, a__2, a__1, c, a__0, a__3);
	output n__474;
	wire n469, n430, n__92, n589, n__29, n616, n607, n__5, n576, n645;
	input b__6, b__5, b__4, a__2, a__1, c, a__0, a__3;
  assign n__474 = ~(n430 | n469);
  assign n430 = ~b__6;
  assign n469 = ~(n__92 & b__5);
  assign n__92 = ~n589;
  assign n589 = ~(n__29 & b__4);
  assign n__29 = ~(n607 | n616);
  assign n607 = ~(a__2 & n__5);
  assign n__5 = ~(n645 | n576);
  assign n645 = ~a__1;
  assign n576 = ~(a__0 & c);
  assign n616 = ~a__3;
endmodule
