// c5.v generated by perl script

module c5 (n__4, b__0, a__0, a__1);
	output n__4;
	wire n645, n647;
	input b__0, a__0, a__1;
  assign n__4 = ~(n647 | n645);
  assign n647 = ~(a__0 & b__0);
  assign n645 = ~a__1;
endmodule
