// c89.v generated by perl script

module c89 (n__88, b__4, b__3, a__3);
	output n__88;
	wire n593, n__25, n616, n631;
	input b__4, b__3, a__3;
  assign n__88 = ~n593;
  assign n593 = ~(n__25 & b__4);
  assign n__25 = ~(n631 | n616);
  assign n631 = ~b__3;
  assign n616 = ~a__3;
endmodule
