// c9.v generated by perl script

module c9 (n__8, c, a__0, b__1);
	output n__8;
	wire n649, n576;
	input c, a__0, b__1;
  assign n__8 = ~(n576 | n649);
  assign n576 = ~(a__0 & c);
  assign n649 = ~b__1;
endmodule
