// c91.v generated by perl script

module c91 (n__90, b__4, a__2, a__1, b__1, a__3);
	output n__90;
	wire n591, n__27, n616, n627, n__3, n649, n645;
	input b__4, a__2, a__1, b__1, a__3;
  assign n__90 = ~n591;
  assign n591 = ~(n__27 & b__4);
  assign n__27 = ~(n627 | n616);
  assign n627 = ~(a__2 & n__3);
  assign n__3 = ~(n645 | n649);
  assign n645 = ~a__1;
  assign n649 = ~b__1;
  assign n616 = ~a__3;
endmodule
