// c2.v generated by perl script

module c2 (code__1, b__1, a__1, n__2, n__1, n__0);
	output code__1;
	wire t_2, N14, t_1;
	input b__1, a__1, n__2, n__1, n__0;
  assign code__1 = N14 ^ t_2;
  assign N14 = a__1 ^ b__1;
  assign t_2 = t_1 ^ n__2;
  assign t_1 = n__0 ^ n__1;
endmodule
