// c5.v generated by perl script

module c5 (code__4, b__4, a__4, n__55, n__54, n__53, n__52, n__51, n__50, n__49, n__48, n__47, n__46, n__45, n__44, n__43, n__42, n__41, n__40, n__39, n__38, n__37, n__36, n__35, n__34, n__33, n__32, n__31, n__30, n__29, n__28, n__27, n__26, n__25);
	output code__4;
	wire t_55, N17, t_54, t_53, t_52, t_51, t_50, t_49, t_48, t_47, t_46, t_45, t_44, t_43, t_42, t_41, t_40, t_39, t_38, t_37, t_36, t_35, t_34, t_33, t_32, t_31, t_30, t_29, t_28, t_27, t_26;
	input b__4, a__4, n__55, n__54, n__53, n__52, n__51, n__50, n__49, n__48, n__47, n__46, n__45, n__44, n__43, n__42, n__41, n__40, n__39, n__38, n__37, n__36, n__35, n__34, n__33, n__32, n__31, n__30, n__29, n__28, n__27, n__26, n__25;
  assign code__4 = N17 ^ t_55;
  assign N17 = a__4 ^ b__4;
  assign t_55 = t_54 ^ n__55;
  assign t_54 = t_53 ^ n__54;
  assign t_53 = t_52 ^ n__53;
  assign t_52 = t_51 ^ n__52;
  assign t_51 = t_50 ^ n__51;
  assign t_50 = t_49 ^ n__50;
  assign t_49 = t_48 ^ n__49;
  assign t_48 = t_47 ^ n__48;
  assign t_47 = t_46 ^ n__47;
  assign t_46 = t_45 ^ n__46;
  assign t_45 = t_44 ^ n__45;
  assign t_44 = t_43 ^ n__44;
  assign t_43 = t_42 ^ n__43;
  assign t_42 = t_41 ^ n__42;
  assign t_41 = t_40 ^ n__41;
  assign t_40 = t_39 ^ n__40;
  assign t_39 = t_38 ^ n__39;
  assign t_38 = t_37 ^ n__38;
  assign t_37 = t_36 ^ n__37;
  assign t_36 = t_35 ^ n__36;
  assign t_35 = t_34 ^ n__35;
  assign t_34 = t_33 ^ n__34;
  assign t_33 = t_32 ^ n__33;
  assign t_32 = t_31 ^ n__32;
  assign t_31 = t_30 ^ n__31;
  assign t_30 = t_29 ^ n__30;
  assign t_29 = t_28 ^ n__29;
  assign t_28 = t_27 ^ n__28;
  assign t_27 = t_26 ^ n__27;
  assign t_26 = n__25 ^ n__26;
endmodule
