// c144.v generated by perl script

module c144 (n__143, a__5, a__4, b__3, a__2, c, a__0, b__1);
	output n__143;
	wire n545, n__79, n603, n__47, n580, n631, n__8, n649, n576;
	input a__5, a__4, b__3, a__2, c, a__0, b__1;
  assign n__143 = ~n545;
  assign n545 = ~(a__5 & n__79);
  assign n__79 = ~n603;
  assign n603 = ~(n__47 & a__4);
  assign n__47 = ~(n631 | n580);
  assign n631 = ~b__3;
  assign n580 = ~(n__8 & a__2);
  assign n__8 = ~(n576 | n649);
  assign n576 = ~(a__0 & c);
  assign n649 = ~b__1;
endmodule
