// c15.v generated by perl script

module c15 (n__14, a__2, a__1, b__0, c);
	output n__14;
	wire n596, n__6, n570, n645;
	input a__2, a__1, b__0, c;
  assign n__14 = ~n596;
  assign n596 = ~(n__6 & a__2);
  assign n__6 = ~(n645 | n570);
  assign n645 = ~a__1;
  assign n570 = ~(c & b__0);
endmodule
