// c21.v generated by perl script

module c21 (n__20, b__2, a__1, c, a__0);
	output n__20;
	wire n575, n__5, n576, n645;
	input b__2, a__1, c, a__0;
  assign n__20 = ~n575;
  assign n575 = ~(b__2 & n__5);
  assign n__5 = ~(n645 | n576);
  assign n645 = ~a__1;
  assign n576 = ~(a__0 & c);
endmodule
