// c24.v generated by perl script

module c24 (n__23, b__2, c, a__0, b__1);
	output n__23;
	wire n572, n__8, n649, n576;
	input b__2, c, a__0, b__1;
  assign n__23 = ~n572;
  assign n572 = ~(n__8 & b__2);
  assign n__8 = ~(n576 | n649);
  assign n576 = ~(a__0 & c);
  assign n649 = ~b__1;
endmodule
