// c248.v generated by perl script

module c248 (n__247, b__5, a__5, a__6);
	output n__247;
	wire n433, n569;
	input b__5, a__5, a__6;
  assign n__247 = ~(n569 | n433);
  assign n569 = ~(a__5 & b__5);
  assign n433 = ~a__6;
endmodule
