// c272.v generated by perl script

module c272 (n__271, a__5, a__4, b__3, a__2, c, a__0, b__1, a__6);
	output n__271;
	wire n434, n545, n__79, n603, n__47, n580, n631, n__8, n649, n576;
	input a__5, a__4, b__3, a__2, c, a__0, b__1, a__6;
  assign n__271 = ~(n545 | n434);
  assign n545 = ~(a__5 & n__79);
  assign n__79 = ~n603;
  assign n603 = ~(n__47 & a__4);
  assign n__47 = ~(n631 | n580);
  assign n631 = ~b__3;
  assign n580 = ~(n__8 & a__2);
  assign n__8 = ~(n576 | n649);
  assign n576 = ~(a__0 & c);
  assign n649 = ~b__1;
  assign n434 = ~a__6;
endmodule
