// c280.v generated by perl script

module c280 (n__279, a__5, a__4, b__2, b__1, b__0, c, b__3, a__6);
	output n__279;
	wire n435, n537, n__87, n594, n__55, n631, n571, n__9, n570, n649;
	input a__5, a__4, b__2, b__1, b__0, c, b__3, a__6;
  assign n__279 = ~(n537 | n435);
  assign n537 = ~(a__5 & n__87);
  assign n__87 = ~n594;
  assign n594 = ~(a__4 & n__55);
  assign n__55 = ~(n571 | n631);
  assign n571 = ~(n__9 & b__2);
  assign n__9 = ~(n649 | n570);
  assign n649 = ~b__1;
  assign n570 = ~(c & b__0);
  assign n631 = ~b__3;
  assign n435 = ~a__6;
endmodule
