// c318.v generated by perl script

module c318 (n__317, b__5, a__4, a__2, a__1, b__0, c, a__3, a__6);
	output n__317;
	wire n438, n499, n__62, n623, n__30, n616, n596, n__6, n570, n645;
	input b__5, a__4, a__2, a__1, b__0, c, a__3, a__6;
  assign n__317 = ~(n499 | n438);
  assign n499 = ~(n__62 & b__5);
  assign n__62 = ~n623;
  assign n623 = ~(a__4 & n__30);
  assign n__30 = ~(n596 | n616);
  assign n596 = ~(n__6 & a__2);
  assign n__6 = ~(n645 | n570);
  assign n645 = ~a__1;
  assign n570 = ~(c & b__0);
  assign n616 = ~a__3;
  assign n438 = ~a__6;
endmodule
