// c348.v generated by perl script

module c348 (n__347, b__5, b__4, a__2, a__1, c, a__0, a__3, a__6);
	output n__347;
	wire n440, n469, n__92, n589, n__29, n616, n607, n__5, n576, n645;
	input b__5, b__4, a__2, a__1, c, a__0, a__3, a__6;
  assign n__347 = ~(n469 | n440);
  assign n469 = ~(n__92 & b__5);
  assign n__92 = ~n589;
  assign n589 = ~(n__29 & b__4);
  assign n__29 = ~(n607 | n616);
  assign n607 = ~(a__2 & n__5);
  assign n__5 = ~(n645 | n576);
  assign n645 = ~a__1;
  assign n576 = ~(a__0 & c);
  assign n616 = ~a__3;
  assign n440 = ~a__6;
endmodule
