// c359.v generated by perl script

module c359 (n__358, b__5, b__4, b__2, b__1, b__0, c, a__3, a__6);
	output n__358;
	wire n441, n458, n__103, n651, n__40, n616, n571, n__9, n570, n649;
	input b__5, b__4, b__2, b__1, b__0, c, a__3, a__6;
  assign n__358 = ~(n458 | n441);
  assign n458 = ~(n__103 & b__5);
  assign n__103 = ~n651;
  assign n651 = ~(n__40 & b__4);
  assign n__40 = ~(n571 | n616);
  assign n571 = ~(n__9 & b__2);
  assign n__9 = ~(n649 | n570);
  assign n649 = ~b__1;
  assign n570 = ~(c & b__0);
  assign n616 = ~a__3;
  assign n441 = ~a__6;
endmodule
