// c37.v generated by perl script

module c37 (n__36, a__3, b__2, a__1, c, a__0);
	output n__36;
	wire n575, n616, n__5, n576, n645;
	input a__3, b__2, a__1, c, a__0;
  assign n__36 = ~(n616 | n575);
  assign n616 = ~a__3;
  assign n575 = ~(b__2 & n__5);
  assign n__5 = ~(n645 | n576);
  assign n645 = ~a__1;
  assign n576 = ~(a__0 & c);
endmodule
