// c376.v generated by perl script

module c376 (n__375, b__6, a__5, b__4, a__4);
	output n__375;
	wire n568, n423, n__56, n632;
	input b__6, a__5, b__4, a__4;
  assign n__375 = ~(n423 | n568);
  assign n423 = ~b__6;
  assign n568 = ~(a__5 & n__56);
  assign n__56 = ~n632;
  assign n632 = ~(a__4 & b__4);
endmodule
