// c381.v generated by perl script

module c381 (n__380, b__6, a__5, a__4, a__2, a__1, c, a__0, a__3);
	output n__380;
	wire n563, n423, n__61, n624, n__29, n616, n607, n__5, n576, n645;
	input b__6, a__5, a__4, a__2, a__1, c, a__0, a__3;
  assign n__380 = ~(n423 | n563);
  assign n423 = ~b__6;
  assign n563 = ~(a__5 & n__61);
  assign n__61 = ~n624;
  assign n624 = ~(a__4 & n__29);
  assign n__29 = ~(n607 | n616);
  assign n607 = ~(a__2 & n__5);
  assign n__5 = ~(n645 | n576);
  assign n645 = ~a__1;
  assign n576 = ~(a__0 & c);
  assign n616 = ~a__3;
endmodule
