// c423.v generated by perl script

module c423 (n__422, b__6, a__5, b__4, b__2, b__1, b__0, c, a__3);
	output n__422;
	wire n521, n426, n__103, n651, n__40, n616, n571, n__9, n570, n649;
	input b__6, a__5, b__4, b__2, b__1, b__0, c, a__3;
  assign n__422 = ~(n426 | n521);
  assign n426 = ~b__6;
  assign n521 = ~(a__5 & n__103);
  assign n__103 = ~n651;
  assign n651 = ~(n__40 & b__4);
  assign n__40 = ~(n571 | n616);
  assign n571 = ~(n__9 & b__2);
  assign n__9 = ~(n649 | n570);
  assign n649 = ~b__1;
  assign n570 = ~(c & b__0);
  assign n616 = ~a__3;
endmodule
