// c48.v generated by perl script

module c48 (n__47, b__3, a__2, c, a__0, b__1);
	output n__47;
	wire n580, n631, n__8, n649, n576;
	input b__3, a__2, c, a__0, b__1;
  assign n__47 = ~(n631 | n580);
  assign n631 = ~b__3;
  assign n580 = ~(n__8 & a__2);
  assign n__8 = ~(n576 | n649);
  assign n576 = ~(a__0 & c);
  assign n649 = ~b__1;
endmodule
