// c49.v generated by perl script

module c49 (n__48, b__3, a__2, b__1, b__0, c);
	output n__48;
	wire n579, n631, n__9, n570, n649;
	input b__3, a__2, b__1, b__0, c;
  assign n__48 = ~(n631 | n579);
  assign n631 = ~b__3;
  assign n579 = ~(a__2 & n__9);
  assign n__9 = ~(n649 | n570);
  assign n649 = ~b__1;
  assign n570 = ~(c & b__0);
endmodule
