// c56.v generated by perl script

module c56 (n__55, b__2, b__1, b__0, c, b__3);
	output n__55;
	wire n631, n571, n__9, n570, n649;
	input b__2, b__1, b__0, c, b__3;
  assign n__55 = ~(n571 | n631);
  assign n571 = ~(n__9 & b__2);
  assign n__9 = ~(n649 | n570);
  assign n649 = ~b__1;
  assign n570 = ~(c & b__0);
  assign n631 = ~b__3;
endmodule
