# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/danielrb/Dropbox/tesi/rca_adder/vivsyn/rca_decomposed/rca_decomposed.cache/wt [current_project]
set_property parent.project_path /home/danielrb/Dropbox/tesi/rca_adder/vivsyn/rca_decomposed/rca_decomposed.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog /home/danielrb/Dropbox/tesi/rca_adder/src/constants.v
set_property file_type "Verilog Header" [get_files /home/danielrb/Dropbox/tesi/rca_adder/src/constants.v]
read_verilog -library xil_defaultlib {
  /home/danielrb/Dropbox/tesi/rca_adder/src/lin_part.v
  /home/danielrb/Dropbox/tesi/rca_adder/src/nonlin_part.v
  /home/danielrb/Dropbox/tesi/rca_adder/src/decomposed_rca.v
}
synth_design -top decomposed_rca -part xc7z010clg400-1
write_checkpoint -noxdef decomposed_rca.dcp
catch { report_utilization -file decomposed_rca_utilization_synth.rpt -pb decomposed_rca_utilization_synth.pb }
