// c10.v generated by perl script

module c10 (n__9, b__1, b__0, c);
	output n__9;
	wire n570, n649;
	input b__1, b__0, c;
  assign n__9 = ~(n649 | n570);
  assign n649 = ~b__1;
  assign n570 = ~(c & b__0);
endmodule
