// c13.v generated by perl script

module c13 (n__12, a__2, b__0, a__0, a__1);
	output n__12;
	wire n619, n__4, n645, n647;
	input a__2, b__0, a__0, a__1;
  assign n__12 = ~n619;
  assign n619 = ~(a__2 & n__4);
  assign n__4 = ~(n647 | n645);
  assign n647 = ~(a__0 & b__0);
  assign n645 = ~a__1;
endmodule
