// c150.v generated by perl script

module c150 (n__149, a__5, a__4, b__2, b__0, a__0, b__1, b__3);
	output n__149;
	wire n539, n__85, n597, n__53, n631, n573, n__7, n649, n647;
	input a__5, a__4, b__2, b__0, a__0, b__1, b__3;
  assign n__149 = ~n539;
  assign n539 = ~(a__5 & n__85);
  assign n__85 = ~n597;
  assign n597 = ~(n__53 & a__4);
  assign n__53 = ~(n573 | n631);
  assign n573 = ~(n__7 & b__2);
  assign n__7 = ~(n647 | n649);
  assign n647 = ~(a__0 & b__0);
  assign n649 = ~b__1;
  assign n631 = ~b__3;
endmodule
