// c242.v generated by perl script

module c242 (n__241, b__5, b__4, b__3, b__2, a__1, c, a__0);
	output n__241;
	wire n447, n__114, n637, n__51, n575, n631, n__5, n576, n645;
	input b__5, b__4, b__3, b__2, a__1, c, a__0;
  assign n__241 = ~n447;
  assign n447 = ~(n__114 & b__5);
  assign n__114 = ~n637;
  assign n637 = ~(n__51 & b__4);
  assign n__51 = ~(n631 | n575);
  assign n631 = ~b__3;
  assign n575 = ~(b__2 & n__5);
  assign n__5 = ~(n645 | n576);
  assign n645 = ~a__1;
  assign n576 = ~(a__0 & c);
endmodule
