// c278.v generated by perl script

module c278 (n__277, a__5, a__4, b__2, b__0, a__0, b__1, b__3, a__6);
	output n__277;
	wire n435, n539, n__85, n597, n__53, n631, n573, n__7, n649, n647;
	input a__5, a__4, b__2, b__0, a__0, b__1, b__3, a__6;
  assign n__277 = ~(n539 | n435);
  assign n539 = ~(a__5 & n__85);
  assign n__85 = ~n597;
  assign n597 = ~(n__53 & a__4);
  assign n__53 = ~(n573 | n631);
  assign n573 = ~(n__7 & b__2);
  assign n__7 = ~(n647 | n649);
  assign n647 = ~(a__0 & b__0);
  assign n649 = ~b__1;
  assign n631 = ~b__3;
  assign n435 = ~a__6;
endmodule
