// c283.v generated by perl script

module c283 (n__282, a__5, b__4, a__2, a__1, b__1, a__3, a__6);
	output n__282;
	wire n435, n534, n__90, n591, n__27, n616, n627, n__3, n649, n645;
	input a__5, b__4, a__2, a__1, b__1, a__3, a__6;
  assign n__282 = ~(n534 | n435);
  assign n534 = ~(a__5 & n__90);
  assign n__90 = ~n591;
  assign n591 = ~(n__27 & b__4);
  assign n__27 = ~(n627 | n616);
  assign n627 = ~(a__2 & n__3);
  assign n__3 = ~(n645 | n649);
  assign n645 = ~a__1;
  assign n649 = ~b__1;
  assign n616 = ~a__3;
  assign n435 = ~a__6;
endmodule
