// c310.v generated by perl script

module c310 (n__309, a__5, b__4, b__2, c, a__0, b__1, b__3, a__6);
	output n__309;
	wire n437, n507, n__117, n634, n__54, n631, n572, n__8, n649, n576;
	input a__5, b__4, b__2, c, a__0, b__1, b__3, a__6;
  assign n__309 = ~(n507 | n437);
  assign n507 = ~(a__5 & n__117);
  assign n__117 = ~n634;
  assign n634 = ~(n__54 & b__4);
  assign n__54 = ~(n572 | n631);
  assign n572 = ~(n__8 & b__2);
  assign n__8 = ~(n576 | n649);
  assign n576 = ~(a__0 & c);
  assign n649 = ~b__1;
  assign n631 = ~b__3;
  assign n437 = ~a__6;
endmodule
