// c316.v generated by perl script

module c316 (n__315, b__5, a__4, a__2, b__0, a__0, a__1, a__3, a__6);
	output n__315;
	wire n438, n501, n__60, n625, n__28, n616, n619, n__4, n645, n647;
	input b__5, a__4, a__2, b__0, a__0, a__1, a__3, a__6;
  assign n__315 = ~(n501 | n438);
  assign n501 = ~(n__60 & b__5);
  assign n__60 = ~n625;
  assign n625 = ~(a__4 & n__28);
  assign n__28 = ~(n619 | n616);
  assign n619 = ~(a__2 & n__4);
  assign n__4 = ~(n647 | n645);
  assign n647 = ~(a__0 & b__0);
  assign n645 = ~a__1;
  assign n616 = ~a__3;
  assign n438 = ~a__6;
endmodule
