// c329.v generated by perl script

module c329 (n__328, b__5, a__4, b__3, b__2, a__2, a__6);
	output n__328;
	wire n439, n488, n__73, n610, n__41, n629, n631;
	input b__5, a__4, b__3, b__2, a__2, a__6;
  assign n__328 = ~(n488 | n439);
  assign n488 = ~(n__73 & b__5);
  assign n__73 = ~n610;
  assign n610 = ~(n__41 & a__4);
  assign n__41 = ~(n631 | n629);
  assign n631 = ~b__3;
  assign n629 = ~(a__2 & b__2);
  assign n439 = ~a__6;
endmodule
