// c332.v generated by perl script

module c332 (n__331, b__5, a__4, b__3, a__2, a__1, c, a__0, a__6);
	output n__331;
	wire n439, n485, n__76, n606, n__44, n607, n631, n__5, n576, n645;
	input b__5, a__4, b__3, a__2, a__1, c, a__0, a__6;
  assign n__331 = ~(n485 | n439);
  assign n485 = ~(n__76 & b__5);
  assign n__76 = ~n606;
  assign n606 = ~(n__44 & a__4);
  assign n__44 = ~(n631 | n607);
  assign n631 = ~b__3;
  assign n607 = ~(a__2 & n__5);
  assign n__5 = ~(n645 | n576);
  assign n645 = ~a__1;
  assign n576 = ~(a__0 & c);
  assign n439 = ~a__6;
endmodule
