// c345.v generated by perl script

module c345 (n__344, b__5, b__4, b__2, a__2, a__3, a__6);
	output n__344;
	wire n440, n472, n__89, n592, n__26, n616, n629;
	input b__5, b__4, b__2, a__2, a__3, a__6;
  assign n__344 = ~(n472 | n440);
  assign n472 = ~(n__89 & b__5);
  assign n__89 = ~n592;
  assign n592 = ~(n__26 & b__4);
  assign n__26 = ~(n629 | n616);
  assign n629 = ~(a__2 & b__2);
  assign n616 = ~a__3;
  assign n440 = ~a__6;
endmodule
