// c364.v generated by perl script

module c364 (n__363, b__5, b__4, b__3, a__2, a__1, b__0, c, a__6);
	output n__363;
	wire n442, n453, n__108, n643, n__45, n596, n631, n__6, n570, n645;
	input b__5, b__4, b__3, a__2, a__1, b__0, c, a__6;
  assign n__363 = ~(n453 | n442);
  assign n453 = ~(n__108 & b__5);
  assign n__108 = ~n643;
  assign n643 = ~(n__45 & b__4);
  assign n__45 = ~(n631 | n596);
  assign n631 = ~b__3;
  assign n596 = ~(n__6 & a__2);
  assign n__6 = ~(n645 | n570);
  assign n645 = ~a__1;
  assign n570 = ~(c & b__0);
  assign n442 = ~a__6;
endmodule
