// c365.v generated by perl script

module c365 (n__364, b__5, b__4, b__3, a__2, b__0, a__0, b__1, a__6);
	output n__364;
	wire n442, n452, n__109, n642, n__46, n585, n631, n__7, n649, n647;
	input b__5, b__4, b__3, a__2, b__0, a__0, b__1, a__6;
  assign n__364 = ~(n452 | n442);
  assign n452 = ~(n__109 & b__5);
  assign n__109 = ~n642;
  assign n642 = ~(n__46 & b__4);
  assign n__46 = ~(n631 | n585);
  assign n631 = ~b__3;
  assign n585 = ~(n__7 & a__2);
  assign n__7 = ~(n647 | n649);
  assign n647 = ~(a__0 & b__0);
  assign n649 = ~b__1;
  assign n442 = ~a__6;
endmodule
