// c375.v generated by perl script

module c375 (n__374, b__6, b__5, a__5);
	output n__374;
	wire n569, n423;
	input b__6, b__5, a__5;
  assign n__374 = ~(n423 | n569);
  assign n423 = ~b__6;
  assign n569 = ~(a__5 & b__5);
endmodule
