// c380.v generated by perl script

module c380 (n__379, b__6, a__5, a__4, a__2, b__0, a__0, a__1, a__3);
	output n__379;
	wire n564, n423, n__60, n625, n__28, n616, n619, n__4, n645, n647;
	input b__6, a__5, a__4, a__2, b__0, a__0, a__1, a__3;
  assign n__379 = ~(n423 | n564);
  assign n423 = ~b__6;
  assign n564 = ~(a__5 & n__60);
  assign n__60 = ~n625;
  assign n625 = ~(a__4 & n__28);
  assign n__28 = ~(n619 | n616);
  assign n619 = ~(a__2 & n__4);
  assign n__4 = ~(n647 | n645);
  assign n647 = ~(a__0 & b__0);
  assign n645 = ~a__1;
  assign n616 = ~a__3;
endmodule
