// c461.v generated by perl script

module c461 (n__460, b__6, b__5, a__4, b__3, a__2, b__0, a__0, b__1);
	output n__460;
	wire n483, n429, n__78, n604, n__46, n585, n631, n__7, n649, n647;
	input b__6, b__5, a__4, b__3, a__2, b__0, a__0, b__1;
  assign n__460 = ~(n429 | n483);
  assign n429 = ~b__6;
  assign n483 = ~(n__78 & b__5);
  assign n__78 = ~n604;
  assign n604 = ~(n__46 & a__4);
  assign n__46 = ~(n631 | n585);
  assign n631 = ~b__3;
  assign n585 = ~(n__7 & a__2);
  assign n__7 = ~(n647 | n649);
  assign n647 = ~(a__0 & b__0);
  assign n649 = ~b__1;
endmodule
