// c491.v generated by perl script

module c491 (n__490, b__6, b__5, b__4, b__3, a__2, a__1, b__0, c);
	output n__490;
	wire n453, n432, n__108, n643, n__45, n596, n631, n__6, n570, n645;
	input b__6, b__5, b__4, b__3, a__2, a__1, b__0, c;
  assign n__490 = ~(n432 | n453);
  assign n432 = ~b__6;
  assign n453 = ~(n__108 & b__5);
  assign n__108 = ~n643;
  assign n643 = ~(n__45 & b__4);
  assign n__45 = ~(n631 | n596);
  assign n631 = ~b__3;
  assign n596 = ~(n__6 & a__2);
  assign n__6 = ~(n645 | n570);
  assign n645 = ~a__1;
  assign n570 = ~(c & b__0);
endmodule
