// c496.v generated by perl script

module c496 (n__495, b__6, b__5, b__4, b__3, b__2, b__0, a__0, a__1);
	output n__495;
	wire n448, n432, n__113, n638, n__50, n577, n631, n__4, n645, n647;
	input b__6, b__5, b__4, b__3, b__2, b__0, a__0, a__1;
  assign n__495 = ~(n432 | n448);
  assign n432 = ~b__6;
  assign n448 = ~(n__113 & b__5);
  assign n__113 = ~n638;
  assign n638 = ~(n__50 & b__4);
  assign n__50 = ~(n631 | n577);
  assign n631 = ~b__3;
  assign n577 = ~(n__4 & b__2);
  assign n__4 = ~(n647 | n645);
  assign n647 = ~(a__0 & b__0);
  assign n645 = ~a__1;
endmodule
