// c50.v generated by perl script

module c50 (n__49, b__3, b__2, a__1, b__1);
	output n__49;
	wire n578, n631, n__3, n649, n645;
	input b__3, b__2, a__1, b__1;
  assign n__49 = ~(n631 | n578);
  assign n631 = ~b__3;
  assign n578 = ~(n__3 & b__2);
  assign n__3 = ~(n645 | n649);
  assign n645 = ~a__1;
  assign n649 = ~b__1;
endmodule
