// c51.v generated by perl script

module c51 (n__50, b__3, b__2, b__0, a__0, a__1);
	output n__50;
	wire n577, n631, n__4, n645, n647;
	input b__3, b__2, b__0, a__0, a__1;
  assign n__50 = ~(n631 | n577);
  assign n631 = ~b__3;
  assign n577 = ~(n__4 & b__2);
  assign n__4 = ~(n647 | n645);
  assign n647 = ~(a__0 & b__0);
  assign n645 = ~a__1;
endmodule
