// c55.v generated by perl script

module c55 (n__54, b__2, c, a__0, b__1, b__3);
	output n__54;
	wire n631, n572, n__8, n649, n576;
	input b__2, c, a__0, b__1, b__3;
  assign n__54 = ~(n572 | n631);
  assign n572 = ~(n__8 & b__2);
  assign n__8 = ~(n576 | n649);
  assign n576 = ~(a__0 & c);
  assign n649 = ~b__1;
  assign n631 = ~b__3;
endmodule
