// c59.v generated by perl script

module c59 (n__58, a__4, b__2, a__2, a__3);
	output n__58;
	wire n628, n__26, n616, n629;
	input a__4, b__2, a__2, a__3;
  assign n__58 = ~n628;
  assign n628 = ~(a__4 & n__26);
  assign n__26 = ~(n629 | n616);
  assign n629 = ~(a__2 & b__2);
  assign n616 = ~a__3;
endmodule
