// c7.v generated by perl script

module c7 (n__6, a__1, b__0, c);
	output n__6;
	wire n570, n645;
	input a__1, b__0, c;
  assign n__6 = ~(n645 | n570);
  assign n645 = ~a__1;
  assign n570 = ~(c & b__0);
endmodule
