// c3.v generated by perl script

module c3 (s__2, b__2, a__2, n__9, n__8, n__7, n__6, n__5, n__4, n__3);
	output s__2;
	wire t_9, N2, t_8, t_7, t_6, t_5, t_4;
	input b__2, a__2, n__9, n__8, n__7, n__6, n__5, n__4, n__3;
  assign s__2 = N2 ^ t_9;
  assign N2 = a__2 ^ b__2;
  assign t_9 = t_8 ^ n__9;
  assign t_8 = t_7 ^ n__8;
  assign t_7 = t_6 ^ n__7;
  assign t_6 = t_5 ^ n__6;
  assign t_5 = t_4 ^ n__5;
  assign t_4 = n__3 ^ n__4;
endmodule
