# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /user/erasmus/danielrb/Dropbox/Tesi/cla_adder/opt_decomposed/viv/viv_synth/viv_synth.cache/wt [current_project]
set_property parent.project_path /user/erasmus/danielrb/Dropbox/Tesi/cla_adder/opt_decomposed/viv/viv_synth/viv_synth.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
read_verilog -library xil_defaultlib {
  /user/erasmus/danielrb/Dropbox/Tesi/cla_adder/opt_decomposed/gen_nonlinear_part.v
  /user/erasmus/danielrb/Dropbox/Tesi/cla_adder/opt_decomposed/gen_linear_part.v
  /user/erasmus/danielrb/Dropbox/Tesi/cla_adder/opt_decomposed/gen_cla_decomposed.v
}
synth_design -top gen_cla_decomposed -part xc7z010clg400-1
write_checkpoint -noxdef gen_cla_decomposed.dcp
catch { report_utilization -file gen_cla_decomposed_utilization_synth.rpt -pb gen_cla_decomposed_utilization_synth.pb }
