// c106.v generated by perl script

module c106 (n__105, b__4, b__3, a__2, a__1, b__1);
	output n__105;
	wire n648, n__42, n627, n631, n__3, n649, n645;
	input b__4, b__3, a__2, a__1, b__1;
  assign n__105 = ~n648;
  assign n648 = ~(n__42 & b__4);
  assign n__42 = ~(n631 | n627);
  assign n631 = ~b__3;
  assign n627 = ~(a__2 & n__3);
  assign n__3 = ~(n645 | n649);
  assign n645 = ~a__1;
  assign n649 = ~b__1;
endmodule
