// c14.v generated by perl script

module c14 (n__13, a__2, a__1, c, a__0);
	output n__13;
	wire n607, n__5, n576, n645;
	input a__2, a__1, c, a__0;
  assign n__13 = ~n607;
  assign n607 = ~(a__2 & n__5);
  assign n__5 = ~(n645 | n576);
  assign n645 = ~a__1;
  assign n576 = ~(a__0 & c);
endmodule
