// c145.v generated by perl script

module c145 (n__144, a__5, a__4, b__3, a__2, b__1, b__0, c);
	output n__144;
	wire n544, n__80, n602, n__48, n579, n631, n__9, n570, n649;
	input a__5, a__4, b__3, a__2, b__1, b__0, c;
  assign n__144 = ~n544;
  assign n544 = ~(a__5 & n__80);
  assign n__80 = ~n602;
  assign n602 = ~(n__48 & a__4);
  assign n__48 = ~(n631 | n579);
  assign n631 = ~b__3;
  assign n579 = ~(a__2 & n__9);
  assign n__9 = ~(n649 | n570);
  assign n649 = ~b__1;
  assign n570 = ~(c & b__0);
endmodule
