// c178.v generated by perl script

module c178 (n__177, a__5, b__4, b__3, b__2, b__0, a__0, a__1);
	output n__177;
	wire n511, n__113, n638, n__50, n577, n631, n__4, n645, n647;
	input a__5, b__4, b__3, b__2, b__0, a__0, a__1;
  assign n__177 = ~n511;
  assign n511 = ~(a__5 & n__113);
  assign n__113 = ~n638;
  assign n638 = ~(n__50 & b__4);
  assign n__50 = ~(n631 | n577);
  assign n631 = ~b__3;
  assign n577 = ~(n__4 & b__2);
  assign n__4 = ~(n647 | n645);
  assign n647 = ~(a__0 & b__0);
  assign n645 = ~a__1;
endmodule
