// c20.v generated by perl script

module c20 (n__19, b__2, b__0, a__0, a__1);
	output n__19;
	wire n577, n__4, n645, n647;
	input b__2, b__0, a__0, a__1;
  assign n__19 = ~n577;
  assign n577 = ~(n__4 & b__2);
  assign n__4 = ~(n647 | n645);
  assign n647 = ~(a__0 & b__0);
  assign n645 = ~a__1;
endmodule
