// c201.v generated by perl script

module c201 (n__200, b__5, a__4, b__3, b__2, a__2);
	output n__200;
	wire n488, n__73, n610, n__41, n629, n631;
	input b__5, a__4, b__3, b__2, a__2;
  assign n__200 = ~n488;
  assign n488 = ~(n__73 & b__5);
  assign n__73 = ~n610;
  assign n610 = ~(n__41 & a__4);
  assign n__41 = ~(n631 | n629);
  assign n631 = ~b__3;
  assign n629 = ~(a__2 & b__2);
endmodule
