// c205.v generated by perl script

module c205 (n__204, b__5, a__4, b__3, a__2, a__1, b__0, c);
	output n__204;
	wire n484, n__77, n605, n__45, n596, n631, n__6, n570, n645;
	input b__5, a__4, b__3, a__2, a__1, b__0, c;
  assign n__204 = ~n484;
  assign n484 = ~(n__77 & b__5);
  assign n__77 = ~n605;
  assign n605 = ~(n__45 & a__4);
  assign n__45 = ~(n631 | n596);
  assign n631 = ~b__3;
  assign n596 = ~(n__6 & a__2);
  assign n__6 = ~(n645 | n570);
  assign n645 = ~a__1;
  assign n570 = ~(c & b__0);
endmodule
