// c22.v generated by perl script

module c22 (n__21, b__2, a__1, b__0, c);
	output n__21;
	wire n574, n__6, n570, n645;
	input b__2, a__1, b__0, c;
  assign n__21 = ~n574;
  assign n574 = ~(n__6 & b__2);
  assign n__6 = ~(n645 | n570);
  assign n645 = ~a__1;
  assign n570 = ~(c & b__0);
endmodule
