// c247.v generated by perl script

module c247 (n__246, b__6, a__6);
	output n__246;
	wire n433, n423;
	input b__6, a__6;
  assign n__246 = ~(n423 | n433);
  assign n423 = ~b__6;
  assign n433 = ~a__6;
endmodule
