// c265.v generated by perl script

module c265 (n__264, a__5, a__4, b__2, b__1, b__0, c, a__3, a__6);
	output n__264;
	wire n434, n552, n__72, n611, n__40, n616, n571, n__9, n570, n649;
	input a__5, a__4, b__2, b__1, b__0, c, a__3, a__6;
  assign n__264 = ~(n552 | n434);
  assign n552 = ~(a__5 & n__72);
  assign n__72 = ~n611;
  assign n611 = ~(n__40 & a__4);
  assign n__40 = ~(n571 | n616);
  assign n571 = ~(n__9 & b__2);
  assign n__9 = ~(n649 | n570);
  assign n649 = ~b__1;
  assign n570 = ~(c & b__0);
  assign n616 = ~a__3;
  assign n434 = ~a__6;
endmodule
