// c269.v generated by perl script

module c269 (n__268, a__5, a__4, b__3, a__2, a__1, c, a__0, a__6);
	output n__268;
	wire n434, n548, n__76, n606, n__44, n607, n631, n__5, n576, n645;
	input a__5, a__4, b__3, a__2, a__1, c, a__0, a__6;
  assign n__268 = ~(n548 | n434);
  assign n548 = ~(a__5 & n__76);
  assign n__76 = ~n606;
  assign n606 = ~(n__44 & a__4);
  assign n__44 = ~(n631 | n607);
  assign n631 = ~b__3;
  assign n607 = ~(a__2 & n__5);
  assign n__5 = ~(n645 | n576);
  assign n645 = ~a__1;
  assign n576 = ~(a__0 & c);
  assign n434 = ~a__6;
endmodule
