// c282.v generated by perl script

module c282 (n__281, a__5, b__4, b__2, a__2, a__3, a__6);
	output n__281;
	wire n435, n535, n__89, n592, n__26, n616, n629;
	input a__5, b__4, b__2, a__2, a__3, a__6;
  assign n__281 = ~(n535 | n435);
  assign n535 = ~(a__5 & n__89);
  assign n__89 = ~n592;
  assign n592 = ~(n__26 & b__4);
  assign n__26 = ~(n629 | n616);
  assign n629 = ~(a__2 & b__2);
  assign n616 = ~a__3;
  assign n435 = ~a__6;
endmodule
