// c291.v generated by perl script

module c291 (n__290, a__5, b__4, b__2, b__0, a__0, a__1, a__3, a__6);
	output n__290;
	wire n436, n526, n__98, n582, n__35, n616, n577, n__4, n645, n647;
	input a__5, b__4, b__2, b__0, a__0, a__1, a__3, a__6;
  assign n__290 = ~(n526 | n436);
  assign n526 = ~(a__5 & n__98);
  assign n__98 = ~n582;
  assign n582 = ~(n__35 & b__4);
  assign n__35 = ~(n577 | n616);
  assign n577 = ~(n__4 & b__2);
  assign n__4 = ~(n647 | n645);
  assign n647 = ~(a__0 & b__0);
  assign n645 = ~a__1;
  assign n616 = ~a__3;
  assign n436 = ~a__6;
endmodule
