// c295.v generated by perl script

module c295 (n__294, a__5, b__4, b__2, c, a__0, b__1, a__3, a__6);
	output n__294;
	wire n436, n522, n__102, n652, n__39, n616, n572, n__8, n649, n576;
	input a__5, b__4, b__2, c, a__0, b__1, a__3, a__6;
  assign n__294 = ~(n522 | n436);
  assign n522 = ~(a__5 & n__102);
  assign n__102 = ~n652;
  assign n652 = ~(n__39 & b__4);
  assign n__39 = ~(n572 | n616);
  assign n572 = ~(n__8 & b__2);
  assign n__8 = ~(n576 | n649);
  assign n576 = ~(a__0 & c);
  assign n649 = ~b__1;
  assign n616 = ~a__3;
  assign n436 = ~a__6;
endmodule
