// c32.v generated by perl script

module c32 (n__31, a__2, b__0, a__0, b__1, a__3);
	output n__31;
	wire n616, n585, n__7, n649, n647;
	input a__2, b__0, a__0, b__1, a__3;
  assign n__31 = ~(n585 | n616);
  assign n585 = ~(n__7 & a__2);
  assign n__7 = ~(n647 | n649);
  assign n647 = ~(a__0 & b__0);
  assign n649 = ~b__1;
  assign n616 = ~a__3;
endmodule
