// c323.v generated by perl script

module c323 (n__322, b__5, a__4, b__2, b__0, a__0, a__1, a__3, a__6);
	output n__322;
	wire n438, n494, n__67, n617, n__35, n616, n577, n__4, n645, n647;
	input b__5, a__4, b__2, b__0, a__0, a__1, a__3, a__6;
  assign n__322 = ~(n494 | n438);
  assign n494 = ~(n__67 & b__5);
  assign n__67 = ~n617;
  assign n617 = ~(a__4 & n__35);
  assign n__35 = ~(n577 | n616);
  assign n577 = ~(n__4 & b__2);
  assign n__4 = ~(n647 | n645);
  assign n647 = ~(a__0 & b__0);
  assign n645 = ~a__1;
  assign n616 = ~a__3;
  assign n438 = ~a__6;
endmodule
