// c330.v generated by perl script

module c330 (n__329, b__5, a__4, b__3, a__2, a__1, b__1, a__6);
	output n__329;
	wire n439, n487, n__74, n609, n__42, n627, n631, n__3, n649, n645;
	input b__5, a__4, b__3, a__2, a__1, b__1, a__6;
  assign n__329 = ~(n487 | n439);
  assign n487 = ~(n__74 & b__5);
  assign n__74 = ~n609;
  assign n609 = ~(n__42 & a__4);
  assign n__42 = ~(n631 | n627);
  assign n631 = ~b__3;
  assign n627 = ~(a__2 & n__3);
  assign n__3 = ~(n645 | n649);
  assign n645 = ~a__1;
  assign n649 = ~b__1;
  assign n439 = ~a__6;
endmodule
