// c339.v generated by perl script

module c339 (n__338, b__5, a__4, b__3, b__2, a__1, c, a__0, a__6);
	output n__338;
	wire n440, n478, n__83, n599, n__51, n575, n631, n__5, n576, n645;
	input b__5, a__4, b__3, b__2, a__1, c, a__0, a__6;
  assign n__338 = ~(n478 | n440);
  assign n478 = ~(n__83 & b__5);
  assign n__83 = ~n599;
  assign n599 = ~(n__51 & a__4);
  assign n__51 = ~(n631 | n575);
  assign n631 = ~b__3;
  assign n575 = ~(b__2 & n__5);
  assign n__5 = ~(n645 | n576);
  assign n645 = ~a__1;
  assign n576 = ~(a__0 & c);
  assign n440 = ~a__6;
endmodule
