// c384.v generated by perl script

module c384 (n__383, b__6, a__5, a__4, a__2, c, a__0, b__1, a__3);
	output n__383;
	wire n560, n423, n__64, n621, n__32, n616, n580, n__8, n649, n576;
	input b__6, a__5, a__4, a__2, c, a__0, b__1, a__3;
  assign n__383 = ~(n423 | n560);
  assign n423 = ~b__6;
  assign n560 = ~(a__5 & n__64);
  assign n__64 = ~n621;
  assign n621 = ~(a__4 & n__32);
  assign n__32 = ~(n580 | n616);
  assign n580 = ~(n__8 & a__2);
  assign n__8 = ~(n576 | n649);
  assign n576 = ~(a__0 & c);
  assign n649 = ~b__1;
  assign n616 = ~a__3;
endmodule
