// c392.v generated by perl script

module c392 (n__391, b__6, a__5, a__4, b__2, b__1, b__0, c, a__3);
	output n__391;
	wire n552, n424, n__72, n611, n__40, n616, n571, n__9, n570, n649;
	input b__6, a__5, a__4, b__2, b__1, b__0, c, a__3;
  assign n__391 = ~(n424 | n552);
  assign n424 = ~b__6;
  assign n552 = ~(a__5 & n__72);
  assign n__72 = ~n611;
  assign n611 = ~(n__40 & a__4);
  assign n__40 = ~(n571 | n616);
  assign n571 = ~(n__9 & b__2);
  assign n__9 = ~(n649 | n570);
  assign n649 = ~b__1;
  assign n570 = ~(c & b__0);
  assign n616 = ~a__3;
endmodule
