// c401.v generated by perl script

module c401 (n__400, b__6, a__5, a__4, b__3, b__2, a__1, b__1);
	output n__400;
	wire n543, n425, n__81, n601, n__49, n578, n631, n__3, n649, n645;
	input b__6, a__5, a__4, b__3, b__2, a__1, b__1;
  assign n__400 = ~(n425 | n543);
  assign n425 = ~b__6;
  assign n543 = ~(a__5 & n__81);
  assign n__81 = ~n601;
  assign n601 = ~(n__49 & a__4);
  assign n__49 = ~(n631 | n578);
  assign n631 = ~b__3;
  assign n578 = ~(n__3 & b__2);
  assign n__3 = ~(n645 | n649);
  assign n645 = ~a__1;
  assign n649 = ~b__1;
endmodule
