// c408.v generated by perl script

module c408 (n__407, b__6, a__5, b__4, b__3, a__3);
	output n__407;
	wire n536, n425, n__88, n593, n__25, n616, n631;
	input b__6, a__5, b__4, b__3, a__3;
  assign n__407 = ~(n425 | n536);
  assign n425 = ~b__6;
  assign n536 = ~(a__5 & n__88);
  assign n__88 = ~n593;
  assign n593 = ~(n__25 & b__4);
  assign n__25 = ~(n631 | n616);
  assign n631 = ~b__3;
  assign n616 = ~a__3;
endmodule
