// c42.v generated by perl script

module c42 (n__41, b__3, b__2, a__2);
	output n__41;
	wire n629, n631;
	input b__3, b__2, a__2;
  assign n__41 = ~(n631 | n629);
  assign n631 = ~b__3;
  assign n629 = ~(a__2 & b__2);
endmodule
