// c422.v generated by perl script

module c422 (n__421, b__6, a__5, b__4, b__2, c, a__0, b__1, a__3);
	output n__421;
	wire n522, n426, n__102, n652, n__39, n616, n572, n__8, n649, n576;
	input b__6, a__5, b__4, b__2, c, a__0, b__1, a__3;
  assign n__421 = ~(n426 | n522);
  assign n426 = ~b__6;
  assign n522 = ~(a__5 & n__102);
  assign n__102 = ~n652;
  assign n652 = ~(n__39 & b__4);
  assign n__39 = ~(n572 | n616);
  assign n572 = ~(n__8 & b__2);
  assign n__8 = ~(n576 | n649);
  assign n576 = ~(a__0 & c);
  assign n649 = ~b__1;
  assign n616 = ~a__3;
endmodule
