// c430.v generated by perl script

module c430 (n__429, b__6, a__5, b__4, b__3, a__2, c, a__0, b__1);
	output n__429;
	wire n514, n427, n__110, n641, n__47, n580, n631, n__8, n649, n576;
	input b__6, a__5, b__4, b__3, a__2, c, a__0, b__1;
  assign n__429 = ~(n427 | n514);
  assign n427 = ~b__6;
  assign n514 = ~(a__5 & n__110);
  assign n__110 = ~n641;
  assign n641 = ~(n__47 & b__4);
  assign n__47 = ~(n631 | n580);
  assign n631 = ~b__3;
  assign n580 = ~(n__8 & a__2);
  assign n__8 = ~(n576 | n649);
  assign n576 = ~(a__0 & c);
  assign n649 = ~b__1;
endmodule
