// c448.v generated by perl script

module c448 (n__447, b__6, b__5, a__4, a__2, b__1, b__0, c, a__3);
	output n__447;
	wire n496, n428, n__65, n620, n__33, n616, n579, n__9, n570, n649;
	input b__6, b__5, a__4, a__2, b__1, b__0, c, a__3;
  assign n__447 = ~(n428 | n496);
  assign n428 = ~b__6;
  assign n496 = ~(n__65 & b__5);
  assign n__65 = ~n620;
  assign n620 = ~(a__4 & n__33);
  assign n__33 = ~(n579 | n616);
  assign n579 = ~(a__2 & n__9);
  assign n__9 = ~(n649 | n570);
  assign n649 = ~b__1;
  assign n570 = ~(c & b__0);
  assign n616 = ~a__3;
endmodule
