// c46.v generated by perl script

module c46 (n__45, b__3, a__2, a__1, b__0, c);
	output n__45;
	wire n596, n631, n__6, n570, n645;
	input b__3, a__2, a__1, b__0, c;
  assign n__45 = ~(n631 | n596);
  assign n631 = ~b__3;
  assign n596 = ~(n__6 & a__2);
  assign n__6 = ~(n645 | n570);
  assign n645 = ~a__1;
  assign n570 = ~(c & b__0);
endmodule
