// c466.v generated by perl script

module c466 (n__465, b__6, b__5, a__4, b__3, b__2, a__1, c, a__0);
	output n__465;
	wire n478, n430, n__83, n599, n__51, n575, n631, n__5, n576, n645;
	input b__6, b__5, a__4, b__3, b__2, a__1, c, a__0;
  assign n__465 = ~(n430 | n478);
  assign n430 = ~b__6;
  assign n478 = ~(n__83 & b__5);
  assign n__83 = ~n599;
  assign n599 = ~(n__51 & a__4);
  assign n__51 = ~(n631 | n575);
  assign n631 = ~b__3;
  assign n575 = ~(b__2 & n__5);
  assign n__5 = ~(n645 | n576);
  assign n645 = ~a__1;
  assign n576 = ~(a__0 & c);
endmodule
