// c480.v generated by perl script

module c480 (n__479, b__6, b__5, b__4, b__2, a__1, b__1, a__3);
	output n__479;
	wire n464, n431, n__97, n583, n__34, n616, n578, n__3, n649, n645;
	input b__6, b__5, b__4, b__2, a__1, b__1, a__3;
  assign n__479 = ~(n431 | n464);
  assign n431 = ~b__6;
  assign n464 = ~(n__97 & b__5);
  assign n__97 = ~n583;
  assign n583 = ~(n__34 & b__4);
  assign n__34 = ~(n578 | n616);
  assign n578 = ~(n__3 & b__2);
  assign n__3 = ~(n645 | n649);
  assign n645 = ~a__1;
  assign n649 = ~b__1;
  assign n616 = ~a__3;
endmodule
