// c71.v generated by perl script

module c71 (n__70, a__4, b__2, b__0, a__0, b__1, a__3);
	output n__70;
	wire n613, n__38, n616, n573, n__7, n649, n647;
	input a__4, b__2, b__0, a__0, b__1, a__3;
  assign n__70 = ~n613;
  assign n613 = ~(n__38 & a__4);
  assign n__38 = ~(n573 | n616);
  assign n573 = ~(n__7 & b__2);
  assign n__7 = ~(n647 | n649);
  assign n647 = ~(a__0 & b__0);
  assign n649 = ~b__1;
  assign n616 = ~a__3;
endmodule
