// c8.v generated by perl script

module c8 (n__7, b__0, a__0, b__1);
	output n__7;
	wire n649, n647;
	input b__0, a__0, b__1;
  assign n__7 = ~(n647 | n649);
  assign n647 = ~(a__0 & b__0);
  assign n649 = ~b__1;
endmodule
