// c2.v generated by perl script

module c2 (s__1, b__1, a__1, n__2, n__1, n__0);
	output s__1;
	wire t_2, N1, t_1;
	input b__1, a__1, n__2, n__1, n__0;
  assign s__1 = N1 ^ t_2;
  assign N1 = a__1 ^ b__1;
  assign t_2 = t_1 ^ n__2;
  assign t_1 = n__0 ^ n__1;
endmodule
